version: '3.7'
services:
  nc_docker:
    build: .
    restart: always
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256M
    ports:
      %s


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.12.0/24
        gateway: 192.168.12.1
