version: '3.7'
services:
  nc_docker:
    container_name: CTF_nc_docker
    build: .
    restart: always
    ports:
      {ports}
    {resource_limit}

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
