version: '2'
services:
  nc_docker:
    build: .
    restart: always
    ports:
      %s
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.12.0/24
        gateway: 192.168.12.1
