version: '3.7'
services:
  nc_docker:
    container_name: CTF_nc_docker
    build: .
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 256M
    ports:
      %s


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.12.0/24
